spring:
  application:
    name: artspectrum
  datasource:
    url: jdbc:postgresql://localhost:5432/db_spectrum
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop
jwt:
  secret:
    access:
      Z5vJWgjUrfyNtc5PMgceVHManIBKdDQWQNTdoVq9uI0cljXr+cYFtBRqDSpXxeJ5JNwgJzAJSly6BUiayMcGZQ==
    refresh:
      whWzmTcUuBBVul3IUxeOTkTcfBVrj+EV+QTq7g126Tl4VV+vvl+2kkepfTBoNpoiYyL9x4BkwHXLD4TBzKAC4g==
server:
  port: 8080
springdoc:
  show-login-endpoint: true